// constants actions type

export const actionsType ={
	//PRODUCTS
	PRODUCT_CREATE:"PRODUCT_CREATE",
	PRODUCT_UPLOAD_ERROR:"PRODUCT_UPLOAD_ERROR",
	PRODUCT_UPLOAD_PROGRESS:"PRODUCT_UPLOAD_PROGRESS",
	PRODUCT_UPLOAD_COMPLETE:"PRODUCT_UPLOAD_COMPLETE",

	//CONFIG
	CONFIG_STORE_NAME:"CONFIG_STORE_NAME",

	//CHAT
	CHAT_TYPING:"CHAT_TYPING",
	CHAT_SEND:"CHAT_SEND",

	//ERROR
	NOTIFICATION_ERROR_FRONTEND:"NOTIFICATION_ERROR_FRONTEND",
	NOTIFICATION_ERROR_BACKEND:"NOTIFICATION_ERROR_BACKEND",
	NOTIFICATION_CLOCK:"NOTIFICATION_CLOCK",

	//NAVIGATE
	NAVIGATE_CHANGE:"NAVIGATE_CHANGE"
}