// constants actions type

export const actionsType ={
	//PRODUCTS
	PRODUCT_FILE:"PRODUCT_FILE",

	//CONFIG
	CONFIG_STORE_NAME:"CONFIG_STORE_NAME",

	//ERROR
	NOTIFICATION_ERROR_FRONTEND:"NOTIFICATION_ERROR_FRONTEND",
	NOTIFICATION_ERROR_BACKEND:"NOTIFICATION_ERROR_BACKEND",
	NOTIFICATION_CLOCK:"NOTIFICATION_CLOCK"
}